/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-06-03 00:03:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.semi;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.common.PageInfo;
import java.util.ArrayList;
import com.kh.member_2.model.vo.MemberUser;
import java.sql.Date;
import java.util.ArrayList;
import com.kh.product.model.vo.Product;

public final class categoryPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/common/menubar.jsp", Long.valueOf(1654184340598L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.member_2.model.vo.MemberUser");
    _jspx_imports_classes.add("com.kh.common.PageInfo");
    _jspx_imports_classes.add("com.kh.product.model.vo.Product");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.sql.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");

    	PageInfo pi =(PageInfo)request.getAttribute("pi");
    
   		int currentPage = pi.getCurrentPage();
		int startPage = pi.getStartPage();
		int endPage = pi.getEndPage();
		int maxPage = pi.getMaxPage();
    	String category = (String)request.getAttribute("category");
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>DS SPORTS</title>\r\n");
      out.write("	\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/Semi/resources/css/categoryPage.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("  .list a{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("  }\r\n");
      out.write("  #catebox{\r\n");
      out.write("    width: 1000px;\r\n");
      out.write("    height: 500px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin-left:700px ;\r\n");
      out.write("    margin-top: 100px;\r\n");
      out.write("    \r\n");
      out.write("  }\r\n");
      out.write("  #catebox #catebox-pr{\r\n");
      out.write("    \r\n");
      out.write("    width: 19%;\r\n");
      out.write("    height: 50%;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("  }\r\n");
      out.write("  #catebox #catebox-pr>img{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 50%;\r\n");
      out.write("  }\r\n");
      out.write("  #catebox #catebox-pr>h4{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 14%;\r\n");
      out.write("    border: 1px #000000 solid;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("  }\r\n");
      out.write("  #catebox-pr img{\r\n");
      out.write("  width:200px;\r\n");
      out.write("  height:200px;\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	 ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    String contextPath = request.getContextPath();
    String alertMsg = "";
	MemberUser loginUser = null;
	int loginN = -1;
	int userNo = -1;
	if(session.getAttribute("loginN")!=null) loginN = (int)session.getAttribute("loginN");
	if(session.getAttribute("loginUser")!=null) loginUser= (MemberUser)session.getAttribute("loginUser");
	if(session.getAttribute("alertMsg")!=null) alertMsg = (String)session.getAttribute("alertMsg");
	ArrayList<Product> pr = (ArrayList<Product>)request.getAttribute("list");
  	if(session.getAttribute("userNo")!=null) userNo = (int)session.getAttribute("userNo");
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>DS SPORTS</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/menubar.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<script>\r\n");
      out.write("		var alertMsg = '");
      out.print(alertMsg);
      out.write("'\r\n");
      out.write("		if(");
      out.print(loginN);
      out.write("==2) {\r\n");
      out.write("			if(window.confirm(\"이미 탈퇴한 회원입니다. 탈퇴 취소 처리 하시겠습니까?\")){\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : \"/Semi/ajaxReturnMember.lo\",\r\n");
      out.write("					data : {userNo : ");
      out.print(userNo);
      out.write("},\r\n");
      out.write("					success : function(result){\r\n");
      out.write("						if(result>0) {\r\n");
      out.write("						window.\r\n");
      out.write("						alert(\"정상적으로 탈퇴 취소 처리 되었습니다. 재로그인 해주세요\");\r\n");
      out.write("						window.location.reload(true);\r\n");
      out.write("						}\r\n");
      out.write("					},\r\n");
      out.write("					error : function(){\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("				});				\r\n");
      out.write("			}\r\n");
      out.write("			");
if(session.getAttribute("userNo")!=null) request.getSession().removeAttribute("userNo");
      out.write("\r\n");
      out.write("			");
session.setAttribute("loginN", -1);
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		if(");
      out.print(loginN);
      out.write("==4) {\r\n");
      out.write("			if(window.confirm(\"회원님은 현재 휴면 상태입니다. 휴면해제 처리 하시겠습니까? \")){\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : \"/Semi/ajaxReturnMember.lo\",\r\n");
      out.write("					data : {userNo : ");
      out.print(userNo);
      out.write("},\r\n");
      out.write("					success : function(result){\r\n");
      out.write("						if(result>0) {\r\n");
      out.write("						window.alert(\"정상적으로 해제 처리 되었습니다. 재로그인 해주세요\");\r\n");
      out.write("						window.location.reload(true);\r\n");
      out.write("						}\r\n");
      out.write("					},\r\n");
      out.write("					error : function(){\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			}\r\n");
      out.write("			");
if(session.getAttribute("userNo")!=null) request.getSession().removeAttribute("userNo");
      out.write("\r\n");
      out.write("			");
session.setAttribute("loginN", -1);
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		if(alertMsg != \"\"){\r\n");
      out.write("			window.alert(alertMsg);\r\n");
      out.write("			");
session.removeAttribute("alertMsg");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		//밴, 휴면 자동\r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"/Semi/ajaxMemberManage.lo\"\r\n");
      out.write("			});\r\n");
      out.write("		})\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("	 <!-- HEADER -->\r\n");
      out.write("  <header>\r\n");
      out.write("    <div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.print(contextPath );
      out.write("/views/semi/main.jsp\" class=\"logo\"><img src=\"");
      out.print(contextPath );
      out.write("/resources/img/DsSports.png\" alt=\"DS SPORTS\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- top navi -->\r\n");
      out.write("    ");
if(loginUser==null) {
      out.write("\r\n");
      out.write("    <div class=\"top-navi\">\r\n");
      out.write("      <ul class=\"navi\">\r\n");
      out.write("        <li><a href=\"/Semi/views/common/login.jsp\">로그인</a></li>\r\n");
      out.write("        <li><a href=\"/Semi/views/semi/newMember.jsp\">회원가입</a></li>\r\n");
      out.write("        <li><a href=\"");
      out.print(contextPath);
      out.write("/myPage.me\">마이페이지</a></li>\r\n");
      out.write("        <li><a href=\"/Semi/FaqForm.fq\">고객센터</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
} else {
      out.write("\r\n");
      out.write("        <div class=\"top-navi\" style=\"width:500px;\">	\r\n");
      out.write("      <ul class=\"navi\" style=\"width:500px;\">\r\n");
      out.write("        <li style=\"width:160px;font-size:16px;\">");
      out.print(loginUser.getUserName() );
      out.write(" 님 환영합니다</li>\r\n");
      out.write("        <li style=\"width:100px;\"><a href=\"/Semi/loginUser.lo?logout=1\">로그아웃</a></li>\r\n");
      out.write("        <li style=\"width:100px;\"><a href=\"");
      out.print(contextPath);
      out.write("/myPage.me\">마이페이지</a></li>\r\n");
      out.write("        <li><a href=\"/Semi/FaqForm.fq\">고객센터</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("      <!-- input -->\r\n");
      out.write("      <div class=\"search\">\r\n");
      out.write("        <input id=\"search-button\" type=\"text\" placeholder=\"검색\" style=\"font-size: 20px;\">\r\n");
      out.write("        <div class=\"material-icons\">search</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- order -->\r\n");
      out.write("      <div class=\"order\">\r\n");
      out.write("        <div id=\"order\">\r\n");
      out.write("          <a href=\"/Semi/userBasket.bk\">\r\n");
      out.write("            <div class=\"material-symbols-outlined\">\r\n");
      out.write("            shopping_cart\r\n");
      out.write("          </div>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      <div id=\"favor\">\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("          <div class=\"material-symbols-outlined\">\r\n");
      out.write("            favorite\r\n");
      out.write("          </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </header>\r\n");
      out.write("      <!-- navigator -->\r\n");
      out.write("      <div class=\"navigator\">\r\n");
      out.write("        <ul id=\"navi\">\r\n");
      out.write("          <li class=\"menu\"><a href=\"");
      out.print(contextPath);
      out.write("/soccer.pg?cpage=1\" id=\"soccer\">축구</a>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li ><a href=\"");
      out.print(contextPath);
      out.write("/soccer.pg?cpage=1\">축구공</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/soccer.pg?cpage=1\">축구화</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/soccer.pg?cpage=1\">보호장비</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li><a href=\"");
      out.print(contextPath );
      out.write("/boling.pg?cpage=1\">볼링</a>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/boling.pg?cpage=1\">볼링공</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/boling.pg?cpage=1\">볼링화</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/boling.pg?cpage=1\">보호장비</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li><a href=\"");
      out.print(contextPath );
      out.write("/health.pg?cpage=1\">헬스</a>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/health.pg?cpage=1\">스트랩</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/health.pg?cpage=1\">리프팅벨트</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/health.pg?cpage=1\">보호대</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li><a href=\"");
      out.print(contextPath );
      out.write("/cycle.pg?cpage=1\">자전거</a>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/cycle.pg?cpage=1\">자전거</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/cycle.pg?cpage=1\">LED전등</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/cycle.pg?cpage=1\">보호장비</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("<!--           <li><a href=\"#\">할인판매</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li><a href=\"#\">동네헬스장공유</a>\r\n");
      out.write("          </li>-->\r\n");
      out.write("          \r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   ");
for(Product n : pr) {
      out.write("\r\n");
      out.write("   <div class=\"list\">\r\n");
      out.write("    <div class=\"list1\">\r\n");
      out.write("		<a href=\"\"><h3 class=\"cate-top\"></h3></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"list2\">\r\n");
      out.write("		<a href=\"\"><h3 class=\"cate-middle\"></h3></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"list3\">\r\n");
      out.write("		<a href=\"\"><h3 class=\"cate-bottom\"></h3></a>\r\n");
      out.write("    </div>\r\n");
      out.write("   </div>\r\n");
      out.write("	");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("   <div id=\"catebox\">\r\n");
      out.write("          ");
for(Product n : pr) {
      out.write("\r\n");
      out.write("        <div id=\"catebox-pr\">\r\n");
      out.write("          <a href=\"");
      out.print(contextPath);
      out.write("/detail.pr?dt=");
      out.print(n.getProNo());
      out.write("\"><img src='");
      out.print(n.getProImage());
      out.write("'></a><br>\r\n");
      out.write("          <h4>");
      out.print(n.getProName());
      out.write("</h4>\r\n");
      out.write("          <h4>");
      out.print(n.getProPrice());
      out.write("</h4><br>\r\n");
      out.write("        </div>\r\n");
      out.write("          ");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <br><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("        <div class=\"paging-area\" align=\"center\">\r\n");
      out.write("          ");
if(currentPage!=1){ 
      out.write("\r\n");
      out.write("          <button onclick=\"location.href='");
      out.print(contextPath);
      out.write('/');
      out.print(category );
      out.write(".pg?cpage=");
      out.print(currentPage-1);
      out.write("'\">&lt;</button>\r\n");
      out.write("          ");
} 
      out.write("\r\n");
      out.write("          \r\n");
      out.write("          ");
for(int i =startPage; i<=endPage; i++){ 
      out.write("\r\n");
      out.write("      ");
if(i!=currentPage){ 
      out.write("\r\n");
      out.write("              <button onclick=\"location.href='");
      out.print(contextPath);
      out.write('/');
      out.print(category );
      out.write(".pg?cpage=");
      out.print(i);
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print(i );
      out.write("</button>\r\n");
      out.write("                  ");
}else{ 
      out.write("\r\n");
      out.write("          <button disabled>");
      out.print(i );
      out.write("</button>         \r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("          ");
} 
      out.write("\r\n");
      out.write("          \r\n");
      out.write("          ");
if(currentPage!=maxPage){ 
      out.write("\r\n");
      out.write("          <button onclick=\"location.href='");
      out.print(contextPath);
      out.write('/');
      out.print(category );
      out.write(".pg?cpage=");
      out.print(currentPage+1);
      out.write("'\">&gt;</button>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("       <script>\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write(" 			if('");
      out.print(category );
      out.write("'==\"soccer\"){\r\n");
      out.write("                $(\".cate-top\").text(\"축구공\");\r\n");
      out.write("                $(\".cate-middle\").text(\"축구화\");\r\n");
      out.write("                $(\".cate-bottom\").text(\"보호장비\");\r\n");
      out.write("                $(\".list1>a\").attr(\"href\",\"");
      out.print(contextPath);
      out.write("/soccertp.pg?cpage=1\");\r\n");
      out.write("                $(\".list2>a\").attr(\"href\",\"");
      out.print(contextPath);
      out.write("/soccermd.pg?cpage=1\");\r\n");
      out.write("                $(\".list3>a\").attr(\"href\",\"");
      out.print(contextPath);
      out.write("/soccerbt.pg?cpage=1\");\r\n");
      out.write(" 			}\r\n");
      out.write("        	if('");
      out.print(category );
      out.write("'==\"boling\"){\r\n");
      out.write("                $(\".cate-top\").text(\"볼링공\");\r\n");
      out.write("                $(\".cate-middle\").text(\"볼링화\");\r\n");
      out.write("                $(\".cate-bottom\").text(\"보호장비\");\r\n");
      out.write("                $(\".list1>a\").attr(\"href\",\"");
      out.print(contextPath );
      out.write("/boling.pg?cpage=1&tp=21\");\r\n");
      out.write("                $(\".list2>a\").attr(\"href\",\"");
      out.print(contextPath );
      out.write("/boling.pg?cpage=1&tp=22\");\r\n");
      out.write("                $(\".list3>a\").attr(\"href\",\"");
      out.print(contextPath );
      out.write("/boling.pg?cpage=1&tp=23\");\r\n");
      out.write(" 			}\r\n");
      out.write("        \r\n");
      out.write("            	if('");
      out.print(category );
      out.write("'==\"health\"){\r\n");
      out.write("                $(\".cate-top\").text(\"스트랩\");\r\n");
      out.write("                $(\".cate-middle\").text(\"리프팅벨트\");\r\n");
      out.write("                $(\".cate-bottom\").text(\"보호대\");\r\n");
      out.write("                $(\".list1>a\").attr(\"href\",\"");
      out.print(contextPath );
      out.write("/health.pg?cpage=1&tp=31\");\r\n");
      out.write("                $(\".list2>a\").attr(\"href\",\"");
      out.print(contextPath );
      out.write("/health.pg?cpage=1&tp=32\");\r\n");
      out.write("                $(\".list3>a\").attr(\"href\",\"");
      out.print(contextPath );
      out.write("/health.pg?cpage=1&tp=33\");\r\n");
      out.write("              }\r\n");
      out.write("        	if('");
      out.print(category );
      out.write("'==\"cycle\"){\r\n");
      out.write("                $(\".cate-top\").text(\"자전거\");\r\n");
      out.write("                $(\".cate-middle\").text(\"LED전등\");\r\n");
      out.write("                $(\".cate-bottom\").text(\"보호장비\");\r\n");
      out.write("                $(\".list1>a\").attr(\"href\",\"");
      out.print(contextPath );
      out.write("/cycle.pg?cpage=1&tp=41\");\r\n");
      out.write("                $(\".list2>a\").attr(\"href\",\"");
      out.print(contextPath );
      out.write("/cycle.pg?cpage=1&tp=42\");\r\n");
      out.write("                $(\".list3>a\").attr(\"href\",\"");
      out.print(contextPath );
      out.write("/cycle.pg?cpage=1&tp=43\");\r\n");
      out.write(" 			}\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("      </script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
