/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-06-02 16:34:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.semi;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.member_2.model.vo.MemberUser;
import java.sql.Date;
import java.util.ArrayList;
import com.kh.product.model.vo.Product;

public final class newMember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/common/menubar.jsp", Long.valueOf(1654184340598L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.member_2.model.vo.MemberUser");
    _jspx_imports_classes.add("com.kh.product.model.vo.Product");
    _jspx_imports_classes.add("java.sql.Date");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("    \r\n");


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>DS SPORTS</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/Semi/resources/css/login.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    String contextPath = request.getContextPath();
    String alertMsg = "";
	MemberUser loginUser = null;
	int loginN = -1;
	int userNo = -1;
	if(session.getAttribute("loginN")!=null) loginN = (int)session.getAttribute("loginN");
	if(session.getAttribute("loginUser")!=null) loginUser= (MemberUser)session.getAttribute("loginUser");
	if(session.getAttribute("alertMsg")!=null) alertMsg = (String)session.getAttribute("alertMsg");
	ArrayList<Product> pr = (ArrayList<Product>)request.getAttribute("list");
  	if(session.getAttribute("userNo")!=null) userNo = (int)session.getAttribute("userNo");
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>DS SPORTS</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/resources/css/menubar.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<script>\r\n");
      out.write("		var alertMsg = '");
      out.print(alertMsg);
      out.write("'\r\n");
      out.write("		if(");
      out.print(loginN);
      out.write("==2) {\r\n");
      out.write("			if(window.confirm(\"이미 탈퇴한 회원입니다. 탈퇴 취소 처리 하시겠습니까?\")){\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : \"/Semi/ajaxReturnMember.lo\",\r\n");
      out.write("					data : {userNo : ");
      out.print(userNo);
      out.write("},\r\n");
      out.write("					success : function(result){\r\n");
      out.write("						if(result>0) {\r\n");
      out.write("						window.\r\n");
      out.write("						alert(\"정상적으로 탈퇴 취소 처리 되었습니다. 재로그인 해주세요\");\r\n");
      out.write("						window.location.reload(true);\r\n");
      out.write("						}\r\n");
      out.write("					},\r\n");
      out.write("					error : function(){\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("				});				\r\n");
      out.write("			}\r\n");
      out.write("			");
if(session.getAttribute("userNo")!=null) request.getSession().removeAttribute("userNo");
      out.write("\r\n");
      out.write("			");
session.setAttribute("loginN", -1);
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		if(");
      out.print(loginN);
      out.write("==4) {\r\n");
      out.write("			if(window.confirm(\"회원님은 현재 휴면 상태입니다. 휴면해제 처리 하시겠습니까? \")){\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url : \"/Semi/ajaxReturnMember.lo\",\r\n");
      out.write("					data : {userNo : ");
      out.print(userNo);
      out.write("},\r\n");
      out.write("					success : function(result){\r\n");
      out.write("						if(result>0) {\r\n");
      out.write("						window.alert(\"정상적으로 해제 처리 되었습니다. 재로그인 해주세요\");\r\n");
      out.write("						window.location.reload(true);\r\n");
      out.write("						}\r\n");
      out.write("					},\r\n");
      out.write("					error : function(){\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			}\r\n");
      out.write("			");
if(session.getAttribute("userNo")!=null) request.getSession().removeAttribute("userNo");
      out.write("\r\n");
      out.write("			");
session.setAttribute("loginN", -1);
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		if(alertMsg != \"\"){\r\n");
      out.write("			window.alert(alertMsg);\r\n");
      out.write("			");
session.removeAttribute("alertMsg");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		//밴, 휴면 자동\r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"/Semi/ajaxMemberManage.lo\"\r\n");
      out.write("			});\r\n");
      out.write("		})\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("	 <!-- HEADER -->\r\n");
      out.write("  <header>\r\n");
      out.write("    <div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.print(contextPath );
      out.write("/views/semi/main.jsp\" class=\"logo\"><img src=\"");
      out.print(contextPath );
      out.write("/resources/img/DsSports.png\" alt=\"DS SPORTS\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- top navi -->\r\n");
      out.write("    ");
if(loginUser==null) {
      out.write("\r\n");
      out.write("    <div class=\"top-navi\">\r\n");
      out.write("      <ul class=\"navi\">\r\n");
      out.write("        <li><a href=\"/Semi/views/common/login.jsp\">로그인</a></li>\r\n");
      out.write("        <li><a href=\"/Semi/views/semi/newMember.jsp\">회원가입</a></li>\r\n");
      out.write("        <li><a href=\"");
      out.print(contextPath);
      out.write("/myPage.me\">마이페이지</a></li>\r\n");
      out.write("        <li><a href=\"/Semi/FaqForm.fq\">고객센터</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
} else {
      out.write("\r\n");
      out.write("        <div class=\"top-navi\" style=\"width:500px;\">	\r\n");
      out.write("      <ul class=\"navi\" style=\"width:500px;\">\r\n");
      out.write("        <li style=\"width:160px;font-size:16px;\">");
      out.print(loginUser.getUserName() );
      out.write(" 님 환영합니다</li>\r\n");
      out.write("        <li style=\"width:100px;\"><a href=\"/Semi/loginUser.lo?logout=1\">로그아웃</a></li>\r\n");
      out.write("        <li style=\"width:100px;\"><a href=\"");
      out.print(contextPath);
      out.write("/myPage.me\">마이페이지</a></li>\r\n");
      out.write("        <li><a href=\"/Semi/FaqForm.fq\">고객센터</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("      <!-- input -->\r\n");
      out.write("      <div class=\"search\">\r\n");
      out.write("        <input id=\"search-button\" type=\"text\" placeholder=\"검색\" style=\"font-size: 20px;\">\r\n");
      out.write("        <div class=\"material-icons\">search</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- order -->\r\n");
      out.write("      <div class=\"order\">\r\n");
      out.write("        <div id=\"order\">\r\n");
      out.write("          <a href=\"/Semi/userBasket.bk\">\r\n");
      out.write("            <div class=\"material-symbols-outlined\">\r\n");
      out.write("            shopping_cart\r\n");
      out.write("          </div>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      <div id=\"favor\">\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("          <div class=\"material-symbols-outlined\">\r\n");
      out.write("            favorite\r\n");
      out.write("          </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </header>\r\n");
      out.write("      <!-- navigator -->\r\n");
      out.write("      <div class=\"navigator\">\r\n");
      out.write("        <ul id=\"navi\">\r\n");
      out.write("          <li class=\"menu\"><a href=\"");
      out.print(contextPath);
      out.write("/soccer.pg?cpage=1\" id=\"soccer\">축구</a>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li ><a href=\"");
      out.print(contextPath);
      out.write("/soccer.pg?cpage=1\">축구공</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/soccer.pg?cpage=1\">축구화</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/soccer.pg?cpage=1\">보호장비</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li><a href=\"");
      out.print(contextPath );
      out.write("/boling.pg?cpage=1\">볼링</a>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/boling.pg?cpage=1\">볼링공</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/boling.pg?cpage=1\">볼링화</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/boling.pg?cpage=1\">보호장비</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li><a href=\"");
      out.print(contextPath );
      out.write("/health.pg?cpage=1\">헬스</a>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/health.pg?cpage=1\">스트랩</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/health.pg?cpage=1\">리프팅벨트</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/health.pg?cpage=1\">보호대</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li><a href=\"");
      out.print(contextPath );
      out.write("/cycle.pg?cpage=1\">자전거</a>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/cycle.pg?cpage=1\">자전거</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/cycle.pg?cpage=1\">LED전등</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.print(contextPath );
      out.write("/cycle.pg?cpage=1\">보호장비</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("<!--           <li><a href=\"#\">할인판매</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li><a href=\"#\">동네헬스장공유</a>\r\n");
      out.write("          </li>-->\r\n");
      out.write("          \r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"login_content_empty\">\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"login_content1\">\r\n");
      out.write("		<div id=\"login_content1_1\">\r\n");
      out.write("			<h1>회원가입</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("		<form action=\"/Semi/newMemberUser.lo\" method=\"post\" id=\"newMemberUser\">\r\n");
      out.write("		<div id=\"login_content1_2\">\r\n");
      out.write("			<table id=\"login_table\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th width=\"100px\">* 아이디 :</th>\r\n");
      out.write("					<td width=\"50px\"></td>\r\n");
      out.write("					<td width=\"200px\" height=\"30px\" class=\"inputTd\"><input type=\"text\" class=\"form-control\" name=\"userId\" required id=\"\"userId\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" height=\"30px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>* 비밀번호 : </th>\r\n");
      out.write("					<td width=\"50px\"></td>\r\n");
      out.write("					<td class=\"inputTd\"><input type=\"password\" class=\"form-control\" name=\"userPw\" required id=\"userPw\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" height=\"30px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>* 비밀번호 확인 : </th>\r\n");
      out.write("					<td width=\"50px\"></td>\r\n");
      out.write("					<td class=\"inputTd\"><input type=\"password\" class=\"form-control\" name=\"userPwC\" id=\"userPwC\" required></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"3\" height=\"30px\" id=\"userPwcTd\" ></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>* 이름 : </th>\r\n");
      out.write("					<td width=\"50px\"></td>\r\n");
      out.write("					<td class=\"inputTd\"><input type=\"text\" class=\"form-control\" name=\"userName\" id=\"userName\" required></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" height=\"30px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>* 이메일 : </th>\r\n");
      out.write("					<td width=\"50px\"></td>\r\n");
      out.write("					<td class=\"inputTd\"><input type=\"text\" class=\"form-control\" name=\"email\" id=\"email\" required></td>\r\n");
      out.write("					<td width=\"30px\"></td>\r\n");
      out.write("					<td><button type=\"button\" class=\"btn-dark\" id=\"emailCon1\" onclick=\"emailCon();\">인증번호 받기</button></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" height=\"30px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr id=\"emailConfirmTr\" style=\"display:none\">\r\n");
      out.write("					<th>인증번호 :  </th>\r\n");
      out.write("					<td width=\"50px\"></td>\r\n");
      out.write("					<td class=\"inputTd\"><input type=\"text\" class=\"form-control\" name=\"emailConfirm\" id=\"emailConfirm\" required></td>\r\n");
      out.write("					<td width=\"30px\"></td>\r\n");
      out.write("					<td><button type=\"button\" class=\"btn-dark\" id=\"emailConfirm1\" onclick=\"emailConfi();\">인증번호 확인</button></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr id=\"emailConfirmTr2\" style=\"display:none\">\r\n");
      out.write("					<th colspan=\"5\">이메일을 확인해주세요 인증메일이 보이지 않을 경우 스팸함을 확인해주세요</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" height=\"30px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>* 전화번호 : </th>\r\n");
      out.write("					<td width=\"50px\"></td>\r\n");
      out.write("					<td class=\"inputTd\"><input type=\"text\"  oninput=\"this.value = this.value.replace(/[^0-9-.]/g, '').replace(/(\\..*)\\./g, '$1');\" class=\"form-control\" name=\"phone\" id=\"phone\" maxlength=\"13\" required ></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" height=\"30px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr align=\"center\">\r\n");
      out.write("				<th colspan=\"3\">*주소</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" height=\"30px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" width=\"200px\" >\r\n");
      out.write("					<input type=\"text\" id=\"postcode\" placeholder=\"우편번호\" class=\"form-control\" onclick=\"execDaumPostcode()\" name=\"postcode\" readonly required>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td><input type=\"button\" onclick=\"execDaumPostcode()\" value=\"우편번호 찾기\" class=\"btn-secondary\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" height=\"15px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr align=\"center\">\r\n");
      out.write("				<th colspan=\"3\"><input type=\"text\" id=\"roadAddress\" placeholder=\"도로명주소\" class=\"form-control\" name=\"roadAddress\"></th>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" height=\"15px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr align=\"center\">\r\n");
      out.write("				<th colspan=\"3\"><input type=\"text\" id=\"jibunAddress\" placeholder=\"지번주소\" class=\"form-control\" name=\"jibunAddress\"></th>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" height=\"15px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr align=\"center\">\r\n");
      out.write("				<th colspan=\"3\"><input type=\"text\" id=\"detailAddress\" placeholder=\"상세주소\" class=\"form-control\" name=\"detailAddress\" required></th>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" height=\"15px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr align=\"center\">\r\n");
      out.write("				<th colspan=\"3\"><input type=\"text\" id=\"extraAddress\" placeholder=\"참고항목\" class=\"form-control\" name=\"extraAddress\"></td></th>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" height=\"15px\"><span id=\"guide\" style=\"color:#999;display:none\" class=\"form-control\"></span></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" height=\"30px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>* 생년월일 : </th>\r\n");
      out.write("					<td width=\"50px\"></td>\r\n");
      out.write("					<td class=\"inputTd\"><input type=\"date\" class=\"form-control\" name=\"userBirth\" required></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" height=\"30px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>* 성별  : </th>\r\n");
      out.write("					<td width=\"50px\"></td>\r\n");
      out.write("					<td class=\"inputTd\"><select name=\"gender\" class=\"form-control\">\r\n");
      out.write("					<option value=\"M\">남자</option>\r\n");
      out.write("					<option value=\"F\">여자</option>\r\n");
      out.write("					</select></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			</table>\r\n");
      out.write("			<br><br>\r\n");
      out.write("			<button type=\"submit\" style=\"display:none\" id=\"submitBtn\"></button>\r\n");
      out.write("			<button type=\"button\" class=\"btn btn-danger\" onclick=\"newMember();\">회원가입</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    //본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("    function execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var roadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("                var extraRoadAddr = ''; // 참고 항목 변수\r\n");
      out.write("\r\n");
      out.write("                // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                    extraRoadAddr += data.bname;\r\n");
      out.write("                }\r\n");
      out.write("                // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                   extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                }\r\n");
      out.write("                // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                if(extraRoadAddr !== ''){\r\n");
      out.write("                    extraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('postcode').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"roadAddress\").value = roadAddr;\r\n");
      out.write("                document.getElementById(\"jibunAddress\").value = data.jibunAddress;\r\n");
      out.write("                \r\n");
      out.write("                // 참고항목 문자열이 있을 경우 해당 필드에 넣는다.\r\n");
      out.write("                if(roadAddr !== ''){\r\n");
      out.write("                    document.getElementById(\"extraAddress\").value = extraRoadAddr;\r\n");
      out.write("                } else {\r\n");
      out.write("                    document.getElementById(\"extraAddress\").value = '';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                var guideTextBox = document.getElementById(\"guide\");\r\n");
      out.write("                // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\r\n");
      out.write("                if(data.autoRoadAddress) {\r\n");
      out.write("                    var expRoadAddr = data.autoRoadAddress + extraRoadAddr;\r\n");
      out.write("                    guideTextBox.innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';\r\n");
      out.write("                    guideTextBox.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("                } else if(data.autoJibunAddress) {\r\n");
      out.write("                    var expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("                    guideTextBox.innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';\r\n");
      out.write("                    guideTextBox.style.display = 'block';\r\n");
      out.write("                } else {\r\n");
      out.write("                    guideTextBox.innerHTML = '';\r\n");
      out.write("                    guideTextBox.style.display = 'none';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function newMember(){\r\n");
      out.write("    	var newMemberUser = document.getElementById(\"submitBtn\");\r\n");
      out.write("\r\n");
      out.write("    	if($(\"#userPw\").val()!=$(\"#userPwC\").val()){\r\n");
      out.write("    		$(\"#userPwcTd\").text(\"비밀번호 확인이 일치하지 않습니다.\");\r\n");
      out.write("    		document.getElementById(\"userPw\").scrollIntoView(true);\r\n");
      out.write("    	}else{\r\n");
      out.write("    		$.ajax({\r\n");
      out.write("    			url:\"/Semi/ajaxConfirmSign.lo\",\r\n");
      out.write("    			data:{userId : $(\"#userId\").val(),\r\n");
      out.write("    				email : $(\"#email\").val(),\r\n");
      out.write("    				phone : $(\"#phone\").val()},\r\n");
      out.write("    			type : \"post\",\r\n");
      out.write("    			success : function(result){\r\n");
      out.write("    				console.log(result);\r\n");
      out.write("    				if(result==0){\r\n");
      out.write("    					if(document.getElementById(\"emailConfirm1\").disabled==true){\r\n");
      out.write("	    	    			newMemberUser.click();\r\n");
      out.write("    					}else{\r\n");
      out.write("    						window.alert(\"이메일 인증을 완료해주세요\");\r\n");
      out.write("    					}\r\n");
      out.write("    				}else{\r\n");
      out.write("    					window.alert(\"ID, 이메일, 전화번호 중 이미 가입된 정보가 있습니다. 다시 확인해주세요\");\r\n");
      out.write("    				}\r\n");
      out.write("    			},\r\n");
      out.write("    			error : function(){\r\n");
      out.write("    				\r\n");
      out.write("    			}\r\n");
      out.write("    			\r\n");
      out.write("    		})\r\n");
      out.write("    	}\r\n");
      out.write("    }\r\n");
      out.write("    $(function(){\r\n");
      out.write("        $(\"#phone\").on(\"propertychange change keyup paste input\",function(){\r\n");
      out.write("			if($(this).val().length==3 && between($(this).val().substring(0,3),000,999)){\r\n");
      out.write("				var str = $(this).val().substring(0,3);\r\n");
      out.write("				str += \"-\";\r\n");
      out.write("				$(this).val(str);\r\n");
      out.write("			}\r\n");
      out.write("			if($(this).val().length==8 && between($(this).val().substring(4,8),0000,9999)){\r\n");
      out.write("				var str = $(this).val().substring(0,8);\r\n");
      out.write("				str += \"-\";\r\n");
      out.write("				$(this).val(str);\r\n");
      out.write("			}\r\n");
      out.write("				\r\n");
      out.write("        })\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("    function between(x, min, max){\r\n");
      out.write("    	return x>=min && x<=max;\r\n");
      out.write("    }\r\n");
      out.write("    var ConEmail = \"\";\r\n");
      out.write("    var auKey=\"\";\r\n");
      out.write("	function emailCon(){\r\n");
      out.write("		if($(\"#email\").val()==\"\" || $(\"#email\").val().indexOf('@')==-1 ){\r\n");
      out.write("			window.alert(\"올바른 메일 주소를 입력해주세요\");\r\n");
      out.write("		}else{\r\n");
      out.write("		$(\"#emailConfirmTr\").css('display','');\r\n");
      out.write("		$(\"#emailConfirmTr2\").css('display','');\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : \"/Semi/SendMaill.lo\",\r\n");
      out.write("			data :{email : $(\"#email\").val()},\r\n");
      out.write("			type:\"post\",\r\n");
      out.write("			success : function(result){\r\n");
      out.write("				ConEmail = result.ConEmail;\r\n");
      out.write("				auKey = result.auKey;\r\n");
      out.write("			},\r\n");
      out.write("			error : function(){\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function emailConfi(){\r\n");
      out.write("		if($(\"#email\").val()==ConEmail && $(\"#emailConfirm\").val()==auKey){\r\n");
      out.write("			window.alert(\"인증이 완료되었습니다.\")\r\n");
      out.write("			$(\"#email\").prop('readonly',true);\r\n");
      out.write("			$(\"#emailConfirm\").prop('readonly',true);\r\n");
      out.write("			$(\"#emailConfirm1\").attr('disabled',true);\r\n");
      out.write("			$(\"#emailCon1\").attr('disabled',true);		\r\n");
      out.write("			}else{\r\n");
      out.write("				window.alert(\"이메일 혹은 인증번호가 일치하지 않습니다. 다시 인증해주세요\");\r\n");
      out.write("				console.log(ConEmail);\r\n");
      out.write("				console.log(auKey);\r\n");
      out.write("			\r\n");
      out.write("			}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
